require("config.plugin_config.gruvbox")
require("config.plugin_config.lualine")
require("config.plugin_config.nvim-tree")
require("config.plugin_config.nvim-treesitter")
-- require("config.plugin_config.vim-fugitive")
